"""Add question bank models

Revision ID: fce94d47f96b
Revises: 20260317_000002
Create Date: 2026-03-24 14:27:38.319652
"""

from alembic import op
import sqlalchemy as sa


revision = 'fce94d47f96b'
down_revision = '20260317_000002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_bank',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('question_key', sa.String(length=255), nullable=False),
    sa.Column('course_id', sa.String(length=128), nullable=False),
    sa.Column('course_slug', sa.String(length=128), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_option_text', sa.String(), nullable=False),
    sa.Column('short_explanation', sa.String(), nullable=True),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('option_count', sa.Integer(), nullable=False),
    sa.Column('has_latex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('scaled_score', sa.Float(), nullable=False),
    sa.Column('base_score', sa.Float(), nullable=True),
    sa.Column('band', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.String(length=255), nullable=False),
    sa.Column('cognitive_level', sa.String(length=64), nullable=True),
    sa.Column('processing_complexity', sa.Float(), nullable=True),
    sa.Column('distractor_complexity', sa.Float(), nullable=True),
    sa.Column('note_reference', sa.Float(), nullable=True),
    sa.Column('negative_stem', sa.Float(), nullable=True),
    sa.Column('source_checksum', sa.String(length=128), nullable=True),
    sa.Column('render_checksum', sa.String(length=128), nullable=True),
    sa.Column('explanation_asset_key', sa.String(length=512), nullable=True),
    sa.Column('explanation_asset_url', sa.String(length=1024), nullable=True),
    sa.Column('variant_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_key')
    )
    op.create_index(op.f('ix_question_bank_band'), 'question_bank', ['band'], unique=False)
    op.create_index(op.f('ix_question_bank_cognitive_level'), 'question_bank', ['cognitive_level'], unique=False)
    op.create_index(op.f('ix_question_bank_course_id'), 'question_bank', ['course_id'], unique=False)
    op.create_index(op.f('ix_question_bank_course_slug'), 'question_bank', ['course_slug'], unique=False)
    op.create_index(op.f('ix_question_bank_scaled_score'), 'question_bank', ['scaled_score'], unique=False)
    op.create_index(op.f('ix_question_bank_status'), 'question_bank', ['status'], unique=False)
    op.create_index(op.f('ix_question_bank_topic_id'), 'question_bank', ['topic_id'], unique=False)
    op.create_table('student_course_state',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.String(length=128), nullable=False),
    sa.Column('overall_skill', sa.Float(), server_default='2.5', nullable=False),
    sa.Column('topic_skills', sa.JSON(), nullable=False),
    sa.Column('cognitive_profile', sa.JSON(), nullable=False),
    sa.Column('processing_profile', sa.JSON(), nullable=False),
    sa.Column('misconception_flags', sa.JSON(), nullable=False),
    sa.Column('phase', sa.String(length=32), server_default='cold_start', nullable=False),
    sa.Column('total_quizzes_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('exam_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id')
    )
    op.create_index(op.f('ix_student_course_state_course_id'), 'student_course_state', ['course_id'], unique=False)
    op.create_index(op.f('ix_student_course_state_user_id'), 'student_course_state', ['user_id'], unique=False)
    op.create_table('question_asset_variants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('variant_index', sa.Integer(), nullable=False),
    sa.Column('option_order', sa.JSON(), nullable=False),
    sa.Column('question_asset_key', sa.String(length=512), nullable=False),
    sa.Column('question_asset_url', sa.String(length=1024), nullable=False),
    sa.Column('render_checksum', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'variant_index')
    )
    op.create_table('question_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.String(length=128), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('question_key', sa.String(length=255), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('selected_option_ids', sa.JSON(), nullable=False),
    sa.Column('selected_option_text', sa.String(), nullable=True),
    sa.Column('correct_option_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('arrangement_hash', sa.String(length=64), nullable=True),
    sa.Column('config_index', sa.Integer(), nullable=True),
    sa.Column('time_taken_seconds', sa.Float(), nullable=True),
    sa.Column('time_allocated_seconds', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_attempts_course_id'), 'question_attempts', ['course_id'], unique=False)
    op.create_index(op.f('ix_question_attempts_question_key'), 'question_attempts', ['question_key'], unique=False)
    op.create_index(op.f('ix_question_attempts_session_id'), 'question_attempts', ['session_id'], unique=False)
    op.create_index(op.f('ix_question_attempts_user_id'), 'question_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_attempts_user_id'), table_name='question_attempts')
    op.drop_index(op.f('ix_question_attempts_session_id'), table_name='question_attempts')
    op.drop_index(op.f('ix_question_attempts_question_key'), table_name='question_attempts')
    op.drop_index(op.f('ix_question_attempts_course_id'), table_name='question_attempts')
    op.drop_table('question_attempts')
    op.drop_table('question_asset_variants')
    op.drop_index(op.f('ix_student_course_state_user_id'), table_name='student_course_state')
    op.drop_index(op.f('ix_student_course_state_course_id'), table_name='student_course_state')
    op.drop_table('student_course_state')
    op.drop_index(op.f('ix_question_bank_topic_id'), table_name='question_bank')
    op.drop_index(op.f('ix_question_bank_status'), table_name='question_bank')
    op.drop_index(op.f('ix_question_bank_scaled_score'), table_name='question_bank')
    op.drop_index(op.f('ix_question_bank_course_slug'), table_name='question_bank')
    op.drop_index(op.f('ix_question_bank_course_id'), table_name='question_bank')
    op.drop_index(op.f('ix_question_bank_cognitive_level'), table_name='question_bank')
    op.drop_index(op.f('ix_question_bank_band'), table_name='question_bank')
    op.drop_table('question_bank')
    # ### end Alembic commands ###
